/*
 * generated by Xtext 2.11.0
 */
package org.xtext.burst


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BurstStandaloneSetup extends BurstStandaloneSetupGenerated {

	def static void doSetup() {
		new BurstStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
