/*
 * generated by Xtext 2.11.0
 */
package org.xtext.burst.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBurstScopeProvider extends DelegatingScopeProvider {
}
