/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.burst.burst.BurstFactory;
import org.xtext.burst.burst.BurstPackage;
import org.xtext.burst.burst.Call;
import org.xtext.burst.burst.CallMember;
import org.xtext.burst.burst.CallParameterInConcern;
import org.xtext.burst.burst.Concern;
import org.xtext.burst.burst.ConcernElement;
import org.xtext.burst.burst.File;
import org.xtext.burst.burst.Import;
import org.xtext.burst.burst.Intersection;
import org.xtext.burst.burst.Line;
import org.xtext.burst.burst.Member;
import org.xtext.burst.burst.MemberCall;
import org.xtext.burst.burst.MemberInConcern;
import org.xtext.burst.burst.NamedParameter;
import org.xtext.burst.burst.PackageElement;
import org.xtext.burst.burst.Parameter;
import org.xtext.burst.burst.ParameterCall;
import org.xtext.burst.burst.RuleConcern;
import org.xtext.burst.burst.RuleFileElement;
import org.xtext.burst.burst.RuleImport;
import org.xtext.burst.burst.RuleIntersect;
import org.xtext.burst.burst.RulePackage;
import org.xtext.burst.burst.StaticParameter;
import org.xtext.burst.burst.UsageParameter;
import org.xtext.burst.burst.Variable;
import org.xtext.burst.burst.VariableCall;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BurstFactoryImpl extends EFactoryImpl implements BurstFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static BurstFactory init()
  {
    try
    {
      BurstFactory theBurstFactory = (BurstFactory)EPackage.Registry.INSTANCE.getEFactory(BurstPackage.eNS_URI);
      if (theBurstFactory != null)
      {
        return theBurstFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new BurstFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BurstFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case BurstPackage.FILE: return createFile();
      case BurstPackage.RULE_FILE_ELEMENT: return createRuleFileElement();
      case BurstPackage.RULE_IMPORT: return createRuleImport();
      case BurstPackage.RULE_PACKAGE: return createRulePackage();
      case BurstPackage.PACKAGE_ELEMENT: return createPackageElement();
      case BurstPackage.RULE_CONCERN: return createRuleConcern();
      case BurstPackage.CONCERN_ELEMENT: return createConcernElement();
      case BurstPackage.MEMBER: return createMember();
      case BurstPackage.RULE_INTERSECT: return createRuleIntersect();
      case BurstPackage.VARIABLE: return createVariable();
      case BurstPackage.PARAMETER: return createParameter();
      case BurstPackage.NAMED_PARAMETER: return createNamedParameter();
      case BurstPackage.STATIC_PARAMETER: return createStaticParameter();
      case BurstPackage.USAGE_PARAMETER: return createUsageParameter();
      case BurstPackage.LINE: return createLine();
      case BurstPackage.CALL: return createCall();
      case BurstPackage.MEMBER_CALL: return createMemberCall();
      case BurstPackage.VARIABLE_CALL: return createVariableCall();
      case BurstPackage.PARAMETER_CALL: return createParameterCall();
      case BurstPackage.CALL_MEMBER: return createCallMember();
      case BurstPackage.CALL_PARAMETER_IN_CONCERN: return createCallParameterInConcern();
      case BurstPackage.IMPORT: return createImport();
      case BurstPackage.PACKAGE: return createPackage();
      case BurstPackage.CONCERN: return createConcern();
      case BurstPackage.INTERSECTION: return createIntersection();
      case BurstPackage.MEMBER_IN_CONCERN: return createMemberInConcern();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public File createFile()
  {
    FileImpl file = new FileImpl();
    return file;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RuleFileElement createRuleFileElement()
  {
    RuleFileElementImpl ruleFileElement = new RuleFileElementImpl();
    return ruleFileElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RuleImport createRuleImport()
  {
    RuleImportImpl ruleImport = new RuleImportImpl();
    return ruleImport;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RulePackage createRulePackage()
  {
    RulePackageImpl rulePackage = new RulePackageImpl();
    return rulePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PackageElement createPackageElement()
  {
    PackageElementImpl packageElement = new PackageElementImpl();
    return packageElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RuleConcern createRuleConcern()
  {
    RuleConcernImpl ruleConcern = new RuleConcernImpl();
    return ruleConcern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConcernElement createConcernElement()
  {
    ConcernElementImpl concernElement = new ConcernElementImpl();
    return concernElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Member createMember()
  {
    MemberImpl member = new MemberImpl();
    return member;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RuleIntersect createRuleIntersect()
  {
    RuleIntersectImpl ruleIntersect = new RuleIntersectImpl();
    return ruleIntersect;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable createVariable()
  {
    VariableImpl variable = new VariableImpl();
    return variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parameter createParameter()
  {
    ParameterImpl parameter = new ParameterImpl();
    return parameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NamedParameter createNamedParameter()
  {
    NamedParameterImpl namedParameter = new NamedParameterImpl();
    return namedParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StaticParameter createStaticParameter()
  {
    StaticParameterImpl staticParameter = new StaticParameterImpl();
    return staticParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UsageParameter createUsageParameter()
  {
    UsageParameterImpl usageParameter = new UsageParameterImpl();
    return usageParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Line createLine()
  {
    LineImpl line = new LineImpl();
    return line;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Call createCall()
  {
    CallImpl call = new CallImpl();
    return call;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MemberCall createMemberCall()
  {
    MemberCallImpl memberCall = new MemberCallImpl();
    return memberCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VariableCall createVariableCall()
  {
    VariableCallImpl variableCall = new VariableCallImpl();
    return variableCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ParameterCall createParameterCall()
  {
    ParameterCallImpl parameterCall = new ParameterCallImpl();
    return parameterCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CallMember createCallMember()
  {
    CallMemberImpl callMember = new CallMemberImpl();
    return callMember;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CallParameterInConcern createCallParameterInConcern()
  {
    CallParameterInConcernImpl callParameterInConcern = new CallParameterInConcernImpl();
    return callParameterInConcern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.xtext.burst.burst.Package createPackage()
  {
    PackageImpl package_ = new PackageImpl();
    return package_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Concern createConcern()
  {
    ConcernImpl concern = new ConcernImpl();
    return concern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Intersection createIntersection()
  {
    IntersectionImpl intersection = new IntersectionImpl();
    return intersection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MemberInConcern createMemberInConcern()
  {
    MemberInConcernImpl memberInConcern = new MemberInConcernImpl();
    return memberInConcern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BurstPackage getBurstPackage()
  {
    return (BurstPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static BurstPackage getPackage()
  {
    return BurstPackage.eINSTANCE;
  }

} //BurstFactoryImpl
