/**
 * generated by Xtext 2.11.0
 */
package org.xtext.burst.burst.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.burst.burst.BurstPackage;
import org.xtext.burst.burst.CallElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Call Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CallElementImpl extends MinimalEObjectImpl.Container implements CallElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CallElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BurstPackage.Literals.CALL_ELEMENT;
  }

} //CallElementImpl
