/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.burst.burst.BurstPackage;
import org.xtext.burst.burst.IntersectionElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Intersection Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntersectionElementImpl extends MinimalEObjectImpl.Container implements IntersectionElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntersectionElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BurstPackage.Literals.INTERSECTION_ELEMENT;
  }

} //IntersectionElementImpl
