/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.burst.burst.BurstPackage;
import org.xtext.burst.burst.RuleConcern;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rule Concern</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RuleConcernImpl extends PackageElementImpl implements RuleConcern
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RuleConcernImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BurstPackage.Literals.RULE_CONCERN;
  }

} //RuleConcernImpl
