/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.burst.burst.BurstFactory
 * @model kind="package"
 * @generated
 */
public interface BurstPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "burst";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/burst/Burst";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "burst";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BurstPackage eINSTANCE = org.xtext.burst.burst.impl.BurstPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.FileImpl <em>File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.FileImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getFile()
   * @generated
   */
  int FILE = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.RuleFileElementImpl <em>Rule File Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.RuleFileElementImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRuleFileElement()
   * @generated
   */
  int RULE_FILE_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Rule File Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FILE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.RuleImportImpl <em>Rule Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.RuleImportImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRuleImport()
   * @generated
   */
  int RULE_IMPORT = 2;

  /**
   * The number of structural features of the '<em>Rule Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_IMPORT_FEATURE_COUNT = RULE_FILE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.RulePackageImpl <em>Rule Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.RulePackageImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRulePackage()
   * @generated
   */
  int RULE_PACKAGE = 3;

  /**
   * The number of structural features of the '<em>Rule Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_PACKAGE_FEATURE_COUNT = RULE_FILE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.PackageElementImpl <em>Package Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.PackageElementImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getPackageElement()
   * @generated
   */
  int PACKAGE_ELEMENT = 4;

  /**
   * The number of structural features of the '<em>Package Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.RuleConcernImpl <em>Rule Concern</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.RuleConcernImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRuleConcern()
   * @generated
   */
  int RULE_CONCERN = 5;

  /**
   * The number of structural features of the '<em>Rule Concern</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_CONCERN_FEATURE_COUNT = PACKAGE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.ConcernElementImpl <em>Concern Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.ConcernElementImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getConcernElement()
   * @generated
   */
  int CONCERN_ELEMENT = 6;

  /**
   * The number of structural features of the '<em>Concern Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCERN_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.DeclareMemberImpl <em>Declare Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.DeclareMemberImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getDeclareMember()
   * @generated
   */
  int DECLARE_MEMBER = 7;

  /**
   * The number of structural features of the '<em>Declare Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARE_MEMBER_FEATURE_COUNT = CONCERN_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.RuleIntersectImpl <em>Rule Intersect</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.RuleIntersectImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRuleIntersect()
   * @generated
   */
  int RULE_INTERSECT = 8;

  /**
   * The number of structural features of the '<em>Rule Intersect</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_INTERSECT_FEATURE_COUNT = PACKAGE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.DeclareParameterImpl <em>Declare Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.DeclareParameterImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getDeclareParameter()
   * @generated
   */
  int DECLARE_PARAMETER = 9;

  /**
   * The number of structural features of the '<em>Declare Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARE_PARAMETER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.ConcernParameterImpl <em>Concern Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.ConcernParameterImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getConcernParameter()
   * @generated
   */
  int CONCERN_PARAMETER = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCERN_PARAMETER__NAME = 0;

  /**
   * The number of structural features of the '<em>Concern Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCERN_PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.RenamedParameterImpl <em>Renamed Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.RenamedParameterImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRenamedParameter()
   * @generated
   */
  int RENAMED_PARAMETER = 11;

  /**
   * The feature id for the '<em><b>Concern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAMED_PARAMETER__CONCERN = DECLARE_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAMED_PARAMETER__NAME = DECLARE_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Renamed Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAMED_PARAMETER_FEATURE_COUNT = DECLARE_PARAMETER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.IntersectionElementImpl <em>Intersection Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.IntersectionElementImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getIntersectionElement()
   * @generated
   */
  int INTERSECTION_ELEMENT = 12;

  /**
   * The number of structural features of the '<em>Intersection Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.LineImpl <em>Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.LineImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getLine()
   * @generated
   */
  int LINE = 13;

  /**
   * The feature id for the '<em><b>Calls</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__CALLS = INTERSECTION_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_FEATURE_COUNT = INTERSECTION_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.CallImpl <em>Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.CallImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getCall()
   * @generated
   */
  int CALL = 14;

  /**
   * The number of structural features of the '<em>Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.totoImpl <em>toto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.totoImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#gettoto()
   * @generated
   */
  int TOTO = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOTO__NAME = CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>toto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOTO_FEATURE_COUNT = CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.RenamedParameterCallImpl <em>Renamed Parameter Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.RenamedParameterCallImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRenamedParameterCall()
   * @generated
   */
  int RENAMED_PARAMETER_CALL = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAMED_PARAMETER_CALL__NAME = CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Renamed Parameter Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAMED_PARAMETER_CALL_FEATURE_COUNT = CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.ConcernParameterCallImpl <em>Concern Parameter Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.ConcernParameterCallImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getConcernParameterCall()
   * @generated
   */
  int CONCERN_PARAMETER_CALL = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCERN_PARAMETER_CALL__NAME = 0;

  /**
   * The number of structural features of the '<em>Concern Parameter Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCERN_PARAMETER_CALL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.MemberCallImpl <em>Member Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.MemberCallImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getMemberCall()
   * @generated
   */
  int MEMBER_CALL = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_CALL__NAME = 0;

  /**
   * The number of structural features of the '<em>Member Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_CALL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.MemberInConcernImpl <em>Member In Concern</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.MemberInConcernImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getMemberInConcern()
   * @generated
   */
  int MEMBER_IN_CONCERN = 19;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_IN_CONCERN__TARGET = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_IN_CONCERN__NAME = 1;

  /**
   * The number of structural features of the '<em>Member In Concern</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_IN_CONCERN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.ImportImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 20;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = RULE_IMPORT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = RULE_IMPORT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.PackageImpl <em>Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.PackageImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getPackage()
   * @generated
   */
  int PACKAGE = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__NAME = RULE_PACKAGE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE__ELEMENTS = RULE_PACKAGE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_FEATURE_COUNT = RULE_PACKAGE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.ConcernImpl <em>Concern</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.ConcernImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getConcern()
   * @generated
   */
  int CONCERN = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCERN__NAME = RULE_CONCERN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Supertype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCERN__SUPERTYPE = RULE_CONCERN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCERN__ELEMENTS = RULE_CONCERN_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Concern</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCERN_FEATURE_COUNT = RULE_CONCERN_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.MemberImpl <em>Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.MemberImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getMember()
   * @generated
   */
  int MEMBER = 23;

  /**
   * The feature id for the '<em><b>Concern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER__CONCERN = DECLARE_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER__NAME = DECLARE_MEMBER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMBER_FEATURE_COUNT = DECLARE_MEMBER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.burst.burst.impl.IntersectionImpl <em>Intersection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.burst.burst.impl.IntersectionImpl
   * @see org.xtext.burst.burst.impl.BurstPackageImpl#getIntersection()
   * @generated
   */
  int INTERSECTION = 24;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION__NAME = RULE_INTERSECT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION__PARAMETERS = RULE_INTERSECT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Lines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION__LINES = RULE_INTERSECT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Intersection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION_FEATURE_COUNT = RULE_INTERSECT_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.File <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>File</em>'.
   * @see org.xtext.burst.burst.File
   * @generated
   */
  EClass getFile();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.burst.burst.File#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.burst.burst.File#getElements()
   * @see #getFile()
   * @generated
   */
  EReference getFile_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.RuleFileElement <em>Rule File Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule File Element</em>'.
   * @see org.xtext.burst.burst.RuleFileElement
   * @generated
   */
  EClass getRuleFileElement();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.RuleImport <em>Rule Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Import</em>'.
   * @see org.xtext.burst.burst.RuleImport
   * @generated
   */
  EClass getRuleImport();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.RulePackage <em>Rule Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Package</em>'.
   * @see org.xtext.burst.burst.RulePackage
   * @generated
   */
  EClass getRulePackage();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.PackageElement <em>Package Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Element</em>'.
   * @see org.xtext.burst.burst.PackageElement
   * @generated
   */
  EClass getPackageElement();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.RuleConcern <em>Rule Concern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Concern</em>'.
   * @see org.xtext.burst.burst.RuleConcern
   * @generated
   */
  EClass getRuleConcern();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.ConcernElement <em>Concern Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concern Element</em>'.
   * @see org.xtext.burst.burst.ConcernElement
   * @generated
   */
  EClass getConcernElement();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.DeclareMember <em>Declare Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declare Member</em>'.
   * @see org.xtext.burst.burst.DeclareMember
   * @generated
   */
  EClass getDeclareMember();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.RuleIntersect <em>Rule Intersect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Intersect</em>'.
   * @see org.xtext.burst.burst.RuleIntersect
   * @generated
   */
  EClass getRuleIntersect();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.DeclareParameter <em>Declare Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declare Parameter</em>'.
   * @see org.xtext.burst.burst.DeclareParameter
   * @generated
   */
  EClass getDeclareParameter();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.ConcernParameter <em>Concern Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concern Parameter</em>'.
   * @see org.xtext.burst.burst.ConcernParameter
   * @generated
   */
  EClass getConcernParameter();

  /**
   * Returns the meta object for the reference '{@link org.xtext.burst.burst.ConcernParameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.xtext.burst.burst.ConcernParameter#getName()
   * @see #getConcernParameter()
   * @generated
   */
  EReference getConcernParameter_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.RenamedParameter <em>Renamed Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Renamed Parameter</em>'.
   * @see org.xtext.burst.burst.RenamedParameter
   * @generated
   */
  EClass getRenamedParameter();

  /**
   * Returns the meta object for the reference '{@link org.xtext.burst.burst.RenamedParameter#getConcern <em>Concern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Concern</em>'.
   * @see org.xtext.burst.burst.RenamedParameter#getConcern()
   * @see #getRenamedParameter()
   * @generated
   */
  EReference getRenamedParameter_Concern();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.burst.burst.RenamedParameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.burst.burst.RenamedParameter#getName()
   * @see #getRenamedParameter()
   * @generated
   */
  EAttribute getRenamedParameter_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.IntersectionElement <em>Intersection Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intersection Element</em>'.
   * @see org.xtext.burst.burst.IntersectionElement
   * @generated
   */
  EClass getIntersectionElement();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.Line <em>Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line</em>'.
   * @see org.xtext.burst.burst.Line
   * @generated
   */
  EClass getLine();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.burst.burst.Line#getCalls <em>Calls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Calls</em>'.
   * @see org.xtext.burst.burst.Line#getCalls()
   * @see #getLine()
   * @generated
   */
  EReference getLine_Calls();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.Call <em>Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Call</em>'.
   * @see org.xtext.burst.burst.Call
   * @generated
   */
  EClass getCall();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.toto <em>toto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>toto</em>'.
   * @see org.xtext.burst.burst.toto
   * @generated
   */
  EClass gettoto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.burst.burst.toto#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.burst.burst.toto#getName()
   * @see #gettoto()
   * @generated
   */
  EAttribute gettoto_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.RenamedParameterCall <em>Renamed Parameter Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Renamed Parameter Call</em>'.
   * @see org.xtext.burst.burst.RenamedParameterCall
   * @generated
   */
  EClass getRenamedParameterCall();

  /**
   * Returns the meta object for the reference '{@link org.xtext.burst.burst.RenamedParameterCall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.xtext.burst.burst.RenamedParameterCall#getName()
   * @see #getRenamedParameterCall()
   * @generated
   */
  EReference getRenamedParameterCall_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.ConcernParameterCall <em>Concern Parameter Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concern Parameter Call</em>'.
   * @see org.xtext.burst.burst.ConcernParameterCall
   * @generated
   */
  EClass getConcernParameterCall();

  /**
   * Returns the meta object for the reference '{@link org.xtext.burst.burst.ConcernParameterCall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.xtext.burst.burst.ConcernParameterCall#getName()
   * @see #getConcernParameterCall()
   * @generated
   */
  EReference getConcernParameterCall_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.MemberCall <em>Member Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Member Call</em>'.
   * @see org.xtext.burst.burst.MemberCall
   * @generated
   */
  EClass getMemberCall();

  /**
   * Returns the meta object for the reference '{@link org.xtext.burst.burst.MemberCall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.xtext.burst.burst.MemberCall#getName()
   * @see #getMemberCall()
   * @generated
   */
  EReference getMemberCall_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.MemberInConcern <em>Member In Concern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Member In Concern</em>'.
   * @see org.xtext.burst.burst.MemberInConcern
   * @generated
   */
  EClass getMemberInConcern();

  /**
   * Returns the meta object for the reference '{@link org.xtext.burst.burst.MemberInConcern#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see org.xtext.burst.burst.MemberInConcern#getTarget()
   * @see #getMemberInConcern()
   * @generated
   */
  EReference getMemberInConcern_Target();

  /**
   * Returns the meta object for the reference '{@link org.xtext.burst.burst.MemberInConcern#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.xtext.burst.burst.MemberInConcern#getName()
   * @see #getMemberInConcern()
   * @generated
   */
  EReference getMemberInConcern_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.xtext.burst.burst.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.burst.burst.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see org.xtext.burst.burst.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.Package <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package</em>'.
   * @see org.xtext.burst.burst.Package
   * @generated
   */
  EClass getPackage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.burst.burst.Package#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.burst.burst.Package#getName()
   * @see #getPackage()
   * @generated
   */
  EAttribute getPackage_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.burst.burst.Package#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.burst.burst.Package#getElements()
   * @see #getPackage()
   * @generated
   */
  EReference getPackage_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.Concern <em>Concern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concern</em>'.
   * @see org.xtext.burst.burst.Concern
   * @generated
   */
  EClass getConcern();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.burst.burst.Concern#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.burst.burst.Concern#getName()
   * @see #getConcern()
   * @generated
   */
  EAttribute getConcern_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.burst.burst.Concern#getSupertype <em>Supertype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Supertype</em>'.
   * @see org.xtext.burst.burst.Concern#getSupertype()
   * @see #getConcern()
   * @generated
   */
  EReference getConcern_Supertype();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.burst.burst.Concern#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.burst.burst.Concern#getElements()
   * @see #getConcern()
   * @generated
   */
  EReference getConcern_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.Member <em>Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Member</em>'.
   * @see org.xtext.burst.burst.Member
   * @generated
   */
  EClass getMember();

  /**
   * Returns the meta object for the reference '{@link org.xtext.burst.burst.Member#getConcern <em>Concern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Concern</em>'.
   * @see org.xtext.burst.burst.Member#getConcern()
   * @see #getMember()
   * @generated
   */
  EReference getMember_Concern();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.burst.burst.Member#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.burst.burst.Member#getName()
   * @see #getMember()
   * @generated
   */
  EAttribute getMember_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.burst.burst.Intersection <em>Intersection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intersection</em>'.
   * @see org.xtext.burst.burst.Intersection
   * @generated
   */
  EClass getIntersection();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.burst.burst.Intersection#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.burst.burst.Intersection#getName()
   * @see #getIntersection()
   * @generated
   */
  EAttribute getIntersection_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.burst.burst.Intersection#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.xtext.burst.burst.Intersection#getParameters()
   * @see #getIntersection()
   * @generated
   */
  EReference getIntersection_Parameters();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.burst.burst.Intersection#getLines <em>Lines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lines</em>'.
   * @see org.xtext.burst.burst.Intersection#getLines()
   * @see #getIntersection()
   * @generated
   */
  EReference getIntersection_Lines();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BurstFactory getBurstFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.FileImpl <em>File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.FileImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getFile()
     * @generated
     */
    EClass FILE = eINSTANCE.getFile();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILE__ELEMENTS = eINSTANCE.getFile_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.RuleFileElementImpl <em>Rule File Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.RuleFileElementImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRuleFileElement()
     * @generated
     */
    EClass RULE_FILE_ELEMENT = eINSTANCE.getRuleFileElement();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.RuleImportImpl <em>Rule Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.RuleImportImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRuleImport()
     * @generated
     */
    EClass RULE_IMPORT = eINSTANCE.getRuleImport();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.RulePackageImpl <em>Rule Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.RulePackageImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRulePackage()
     * @generated
     */
    EClass RULE_PACKAGE = eINSTANCE.getRulePackage();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.PackageElementImpl <em>Package Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.PackageElementImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getPackageElement()
     * @generated
     */
    EClass PACKAGE_ELEMENT = eINSTANCE.getPackageElement();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.RuleConcernImpl <em>Rule Concern</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.RuleConcernImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRuleConcern()
     * @generated
     */
    EClass RULE_CONCERN = eINSTANCE.getRuleConcern();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.ConcernElementImpl <em>Concern Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.ConcernElementImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getConcernElement()
     * @generated
     */
    EClass CONCERN_ELEMENT = eINSTANCE.getConcernElement();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.DeclareMemberImpl <em>Declare Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.DeclareMemberImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getDeclareMember()
     * @generated
     */
    EClass DECLARE_MEMBER = eINSTANCE.getDeclareMember();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.RuleIntersectImpl <em>Rule Intersect</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.RuleIntersectImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRuleIntersect()
     * @generated
     */
    EClass RULE_INTERSECT = eINSTANCE.getRuleIntersect();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.DeclareParameterImpl <em>Declare Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.DeclareParameterImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getDeclareParameter()
     * @generated
     */
    EClass DECLARE_PARAMETER = eINSTANCE.getDeclareParameter();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.ConcernParameterImpl <em>Concern Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.ConcernParameterImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getConcernParameter()
     * @generated
     */
    EClass CONCERN_PARAMETER = eINSTANCE.getConcernParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCERN_PARAMETER__NAME = eINSTANCE.getConcernParameter_Name();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.RenamedParameterImpl <em>Renamed Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.RenamedParameterImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRenamedParameter()
     * @generated
     */
    EClass RENAMED_PARAMETER = eINSTANCE.getRenamedParameter();

    /**
     * The meta object literal for the '<em><b>Concern</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RENAMED_PARAMETER__CONCERN = eINSTANCE.getRenamedParameter_Concern();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RENAMED_PARAMETER__NAME = eINSTANCE.getRenamedParameter_Name();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.IntersectionElementImpl <em>Intersection Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.IntersectionElementImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getIntersectionElement()
     * @generated
     */
    EClass INTERSECTION_ELEMENT = eINSTANCE.getIntersectionElement();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.LineImpl <em>Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.LineImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getLine()
     * @generated
     */
    EClass LINE = eINSTANCE.getLine();

    /**
     * The meta object literal for the '<em><b>Calls</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINE__CALLS = eINSTANCE.getLine_Calls();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.CallImpl <em>Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.CallImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getCall()
     * @generated
     */
    EClass CALL = eINSTANCE.getCall();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.totoImpl <em>toto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.totoImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#gettoto()
     * @generated
     */
    EClass TOTO = eINSTANCE.gettoto();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOTO__NAME = eINSTANCE.gettoto_Name();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.RenamedParameterCallImpl <em>Renamed Parameter Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.RenamedParameterCallImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getRenamedParameterCall()
     * @generated
     */
    EClass RENAMED_PARAMETER_CALL = eINSTANCE.getRenamedParameterCall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RENAMED_PARAMETER_CALL__NAME = eINSTANCE.getRenamedParameterCall_Name();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.ConcernParameterCallImpl <em>Concern Parameter Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.ConcernParameterCallImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getConcernParameterCall()
     * @generated
     */
    EClass CONCERN_PARAMETER_CALL = eINSTANCE.getConcernParameterCall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCERN_PARAMETER_CALL__NAME = eINSTANCE.getConcernParameterCall_Name();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.MemberCallImpl <em>Member Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.MemberCallImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getMemberCall()
     * @generated
     */
    EClass MEMBER_CALL = eINSTANCE.getMemberCall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMBER_CALL__NAME = eINSTANCE.getMemberCall_Name();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.MemberInConcernImpl <em>Member In Concern</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.MemberInConcernImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getMemberInConcern()
     * @generated
     */
    EClass MEMBER_IN_CONCERN = eINSTANCE.getMemberInConcern();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMBER_IN_CONCERN__TARGET = eINSTANCE.getMemberInConcern_Target();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMBER_IN_CONCERN__NAME = eINSTANCE.getMemberInConcern_Name();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.ImportImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.PackageImpl <em>Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.PackageImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getPackage()
     * @generated
     */
    EClass PACKAGE = eINSTANCE.getPackage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE__NAME = eINSTANCE.getPackage_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE__ELEMENTS = eINSTANCE.getPackage_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.ConcernImpl <em>Concern</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.ConcernImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getConcern()
     * @generated
     */
    EClass CONCERN = eINSTANCE.getConcern();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCERN__NAME = eINSTANCE.getConcern_Name();

    /**
     * The meta object literal for the '<em><b>Supertype</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCERN__SUPERTYPE = eINSTANCE.getConcern_Supertype();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCERN__ELEMENTS = eINSTANCE.getConcern_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.MemberImpl <em>Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.MemberImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getMember()
     * @generated
     */
    EClass MEMBER = eINSTANCE.getMember();

    /**
     * The meta object literal for the '<em><b>Concern</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEMBER__CONCERN = eINSTANCE.getMember_Concern();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMBER__NAME = eINSTANCE.getMember_Name();

    /**
     * The meta object literal for the '{@link org.xtext.burst.burst.impl.IntersectionImpl <em>Intersection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.burst.burst.impl.IntersectionImpl
     * @see org.xtext.burst.burst.impl.BurstPackageImpl#getIntersection()
     * @generated
     */
    EClass INTERSECTION = eINSTANCE.getIntersection();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERSECTION__NAME = eINSTANCE.getIntersection_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERSECTION__PARAMETERS = eINSTANCE.getIntersection_Parameters();

    /**
     * The meta object literal for the '<em><b>Lines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERSECTION__LINES = eINSTANCE.getIntersection_Lines();

  }

} //BurstPackage
