/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Parameter In Concern</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.burst.burst.BurstPackage#getCallParameterInConcern()
 * @model
 * @generated
 */
public interface CallParameterInConcern extends EObject
{
} // CallParameterInConcern
