/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Member In Concern</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.burst.burst.BurstPackage#getCallMemberInConcern()
 * @model
 * @generated
 */
public interface CallMemberInConcern extends Call
{
} // CallMemberInConcern
