/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.burst.burst.Concern#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.burst.burst.Concern#getSupertype <em>Supertype</em>}</li>
 *   <li>{@link org.xtext.burst.burst.Concern#getMembers <em>Members</em>}</li>
 *   <li>{@link org.xtext.burst.burst.Concern#getIntersections <em>Intersections</em>}</li>
 *   <li>{@link org.xtext.burst.burst.Concern#getBuild <em>Build</em>}</li>
 *   <li>{@link org.xtext.burst.burst.Concern#getDestruct <em>Destruct</em>}</li>
 * </ul>
 *
 * @see org.xtext.burst.burst.BurstPackage#getConcern()
 * @model
 * @generated
 */
public interface Concern extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.burst.burst.BurstPackage#getConcern_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.Concern#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Supertype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Supertype</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Supertype</em>' reference.
   * @see #setSupertype(Concern)
   * @see org.xtext.burst.burst.BurstPackage#getConcern_Supertype()
   * @model
   * @generated
   */
  Concern getSupertype();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.Concern#getSupertype <em>Supertype</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Supertype</em>' reference.
   * @see #getSupertype()
   * @generated
   */
  void setSupertype(Concern value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.burst.burst.Member}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Members</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see org.xtext.burst.burst.BurstPackage#getConcern_Members()
   * @model containment="true"
   * @generated
   */
  EList<Member> getMembers();

  /**
   * Returns the value of the '<em><b>Intersections</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.burst.burst.Intersection}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Intersections</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intersections</em>' containment reference list.
   * @see org.xtext.burst.burst.BurstPackage#getConcern_Intersections()
   * @model containment="true"
   * @generated
   */
  EList<Intersection> getIntersections();

  /**
   * Returns the value of the '<em><b>Build</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Build</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Build</em>' containment reference.
   * @see #setBuild(Build)
   * @see org.xtext.burst.burst.BurstPackage#getConcern_Build()
   * @model containment="true"
   * @generated
   */
  Build getBuild();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.Concern#getBuild <em>Build</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Build</em>' containment reference.
   * @see #getBuild()
   * @generated
   */
  void setBuild(Build value);

  /**
   * Returns the value of the '<em><b>Destruct</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Destruct</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destruct</em>' containment reference.
   * @see #setDestruct(Destruct)
   * @see org.xtext.burst.burst.BurstPackage#getConcern_Destruct()
   * @model containment="true"
   * @generated
   */
  Destruct getDestruct();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.Concern#getDestruct <em>Destruct</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destruct</em>' containment reference.
   * @see #getDestruct()
   * @generated
   */
  void setDestruct(Destruct value);

} // Concern
