/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declare Member</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.burst.burst.BurstPackage#getDeclareMember()
 * @model
 * @generated
 */
public interface DeclareMember extends ConcernElement
{
} // DeclareMember
