/**
 * generated by Xtext 2.11.0
 */
package org.xtext.burst.burst;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.burst.burst.If#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.burst.burst.If#getThenBlock <em>Then Block</em>}</li>
 *   <li>{@link org.xtext.burst.burst.If#getElseBlock <em>Else Block</em>}</li>
 * </ul>
 *
 * @see org.xtext.burst.burst.BurstPackage#getIf()
 * @model
 * @generated
 */
public interface If extends Line
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Call)
   * @see org.xtext.burst.burst.BurstPackage#getIf_Expression()
   * @model containment="true"
   * @generated
   */
  Call getExpression();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.If#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Call value);

  /**
   * Returns the value of the '<em><b>Then Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Block</em>' containment reference.
   * @see #setThenBlock(Line)
   * @see org.xtext.burst.burst.BurstPackage#getIf_ThenBlock()
   * @model containment="true"
   * @generated
   */
  Line getThenBlock();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.If#getThenBlock <em>Then Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Block</em>' containment reference.
   * @see #getThenBlock()
   * @generated
   */
  void setThenBlock(Line value);

  /**
   * Returns the value of the '<em><b>Else Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Block</em>' containment reference.
   * @see #setElseBlock(Line)
   * @see org.xtext.burst.burst.BurstPackage#getIf_ElseBlock()
   * @model containment="true"
   * @generated
   */
  Line getElseBlock();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.If#getElseBlock <em>Else Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Block</em>' containment reference.
   * @see #getElseBlock()
   * @generated
   */
  void setElseBlock(Line value);

} // If
