/**
 * generated by Xtext 2.10.0
 */
package org.xtext.burst.burst;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intersection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.burst.burst.Intersection#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.burst.burst.Intersection#getParams <em>Params</em>}</li>
 *   <li>{@link org.xtext.burst.burst.Intersection#getWithParams <em>With Params</em>}</li>
 *   <li>{@link org.xtext.burst.burst.Intersection#getLines <em>Lines</em>}</li>
 * </ul>
 *
 * @see org.xtext.burst.burst.BurstPackage#getIntersection()
 * @model
 * @generated
 */
public interface Intersection extends RuleIntersect
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.burst.burst.BurstPackage#getIntersection_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.Intersection#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.burst.burst.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.xtext.burst.burst.BurstPackage#getIntersection_Params()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParams();

  /**
   * Returns the value of the '<em><b>With Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.burst.burst.WithParameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>With Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>With Params</em>' containment reference list.
   * @see org.xtext.burst.burst.BurstPackage#getIntersection_WithParams()
   * @model containment="true"
   * @generated
   */
  EList<WithParameter> getWithParams();

  /**
   * Returns the value of the '<em><b>Lines</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.burst.burst.Line}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lines</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lines</em>' containment reference list.
   * @see org.xtext.burst.burst.BurstPackage#getIntersection_Lines()
   * @model containment="true"
   * @generated
   */
  EList<Line> getLines();

} // Intersection
