/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.burst.burst.Line#getCalls <em>Calls</em>}</li>
 * </ul>
 *
 * @see org.xtext.burst.burst.BurstPackage#getLine()
 * @model
 * @generated
 */
public interface Line extends IntersectionElement
{
  /**
   * Returns the value of the '<em><b>Calls</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.burst.burst.Call}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Calls</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calls</em>' containment reference list.
   * @see org.xtext.burst.burst.BurstPackage#getLine_Calls()
   * @model containment="true"
   * @generated
   */
  EList<Call> getCalls();

} // Line
