/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Member Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.burst.burst.MemberCall#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.burst.burst.BurstPackage#getMemberCall()
 * @model
 * @generated
 */
public interface MemberCall extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(Member)
   * @see org.xtext.burst.burst.BurstPackage#getMemberCall_Name()
   * @model
   * @generated
   */
  Member getName();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.MemberCall#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(Member value);

} // MemberCall
