/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.burst.burst.BurstPackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends Variable
{
} // Parameter
