/**
 * generated by Xtext 2.11.0
 */
package org.xtext.burst.burst;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Roles</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.burst.burst.BurstPackage#getRoles()
 * @model
 * @generated
 */
public interface Roles extends FileElement
{
} // Roles
