/**
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.burst;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Package</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.burst.burst.BurstPackage#getRulePackage()
 * @model
 * @generated
 */
public interface RulePackage extends RuleFileElement
{
} // RulePackage
