/**
 * generated by Xtext 2.11.0
 */
package org.xtext.burst.burst;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.burst.burst.Stop#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see org.xtext.burst.burst.BurstPackage#getStop()
 * @model
 * @generated
 */
public interface Stop extends Line
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Call)
   * @see org.xtext.burst.burst.BurstPackage#getStop_Condition()
   * @model containment="true"
   * @generated
   */
  Call getCondition();

  /**
   * Sets the value of the '{@link org.xtext.burst.burst.Stop#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Call value);

} // Stop
