/**
 * generated by Xtext 2.11.0
 */
package org.xtext.burst.burst;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Call</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.burst.burst.BurstPackage#getSubCall()
 * @model
 * @generated
 */
public interface SubCall extends CallElement
{
} // SubCall
