/*
 * generated by Xtext 2.9.0
 */
package org.xtext.burst.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.burst.burst.File

@RunWith(XtextRunner)
@InjectWith(BurstInjectorProvider)
class BurstParsingTest{

	@Inject
	ParseHelper<File> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
